# Form implementation generated from reading ui file 'choose_screen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ChooseWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 781, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.song_id = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.song_id.setGeometry(QtCore.QRect(110, 515, 261, 22))
        self.song_id.setObjectName("song_id")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(580, 510, 171, 28))
        self.start_button.setObjectName("start_button")
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(10, 5, 31, 28))
        self.search_button.setObjectName("search_button")
        self.search_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(50, 7, 541, 22))
        self.search_line.setObjectName("search_line")
        self.search_filter = QtWidgets.QComboBox(parent=self.centralwidget)
        self.search_filter.setGeometry(QtCore.QRect(620, 8, 171, 22))
        self.search_filter.setObjectName("search_filter")
        self.search_filter.addItem("")
        self.search_filter.addItem("")
        self.search_filter.addItem("")
        self.search_filter.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "song Id:"))
        self.start_button.setText(_translate("MainWindow", "Начать"))
        self.search_button.setText(_translate("MainWindow", "⌕"))
        self.search_filter.setItemText(0, _translate("MainWindow", "Исполнитель"))
        self.search_filter.setItemText(1, _translate("MainWindow", "Название трека"))
        self.search_filter.setItemText(2, _translate("MainWindow", "Продолжительность"))
        self.search_filter.setItemText(3, _translate("MainWindow", "Сложность"))
